plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.2.2'
    id 'io.papermc.paperweight.userdev' version '2.0.0-beta.21'
    id 'org.screamingsandals.nms-mapper' version '1.4.10'
}

group = 'top.mcbi.spigot.simplemoddetect'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://jitpack.io' }
    maven { url = 'https://maven.aliyun.com/nexus/content/groups/public/' }
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url = 'https://oss.sonatype.org/content/groups/public/' }
    maven { url = 'https://repo.onarandombox.com/content/groups/public/' }
    maven { url = 'https://libraries.minecraft.net/' }
    maven { url = 'https://repo.codemc.org/repository/maven-public/' }
    maven { url = 'https://repo.dmulloy2.net/repository/public/' }
}

dependencies {
    compileOnly fileTree('libs')
    paperweight.paperDevBundle("26.2.build.+")
    shadow "io.papermc:paperlib:1.0.8"

    compileOnly 'org.projectlombok:lombok:1.18.44'
    annotationProcessor 'org.projectlombok:lombok:1.18.44'
    implementation 'org.jetbrains:annotations:24.0.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

shadowJar {
    configurations = [project.configurations.shadow]
    archiveClassifier = ''
}

build {
    dependsOn(shadowJar)
}

sourceSets.main.java.srcDirs = ['src/generated/java', 'src/main/java']

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.register('copyPlugin', Copy) {
    from "build/libs/SimpleModDetect-${version}.jar"
    into "run/plugins"
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(sourceSets.main.resources.srcDirs) {
        include 'plugin.yml'
        expand version: project.version
    }
}

tasks.register('sourceJar', Jar) {
    from sourceSets.main.allSource
}
