# SimpleModDetect 配置

# 调试模式开关 (true/false)
debug-mode: false

# ==========================================
# 频道检测方式 (通过 custom payload 注册通道检测)
# ==========================================
channel-detect:
  enabled: true
  notify-staff: true
  notification-permission: "simplemoddetect.notify"
  mods:
    Servux:
      # 检测到的频道前缀满足以下任一项时判定命中
      # 可用变量: %player% %mod_name% %detected_mod%
      matches:
        - "servux"
      commands:
        - "litebans:kick %player% Malilib mod是不被允许的"
    JourneyMap:
      matches:
        - "journeymap"
      commands:
        - "litebans:kick %player% JourneyMap mod是不被允许的"
    Baritone:
      matches:
        - "baritone"
      commands:
        - "litebans:kick %player% Baritone是不被允许的"

# ==========================================
# 翻译键检测方式 (通过发送含有特定翻译键的告示牌检测)
# 此方法通过在玩家加入时向其发送特制的告示牌数据包，要求客户端翻译指定的语言键并返回结果，以判断其是否安装了特定模组。
# ==========================================
translation-detect:
  enabled: true
  notify-staff: true
  notification-permission: "simplemoddetect.notify"
  mods:
    Freecam:
      key: "key.freecam.toggle"
      detectionKey: "Toggle Freecam"
      # 当检测到模组时，后台会按顺序执行以下指令。
      # 可用变量: %player% %mod_name% %detected_value%
      commands:
        - "kick %player% Freecam是不被允许的"
    ExampleMod:
      key: "examplemod.lang.key"
      detectionKey: "ExampleMod Key"
      commands:
        - "ban %player% 7d 使用了封禁模组"
